### ISSUE TITLE
Clarify support within StreamField blocks

### ISSUE THREAD

**Issue by chosak** [wagtail/wagtail-editable-help#8]
First, thanks for this useful package!

The README says that this works for any `help_text` argument and, from some simple testing, this seems to work for StreamField blocks, e.g.

```
class Person(blocks.StructBlock):
    name = blocks.CharBlock(
        help_text=HelpText("Person", "name", default="The person's full name")
    )
```

but the use of [`model_label`](https://github.com/wagtail/wagtail-editable-help/blob/9483729b00efd3796da7d00d2e103a3a8385d6b0/wagtail_editable_help/models.py#L17) as the first part of the identifier makes me wonder whether this is truly supported or if there are any gotchas with using this package with blocks instead of models.

**Comment by gasman** [comment]
Thanks for the feedback @chosak! `HelpText` is indeed supported on StreamField blocks (and the tests cover that usage too, so it's not going to break without us knowing) - have now updated the readme to clarify.
